name: Develop - Client Build and Push

on:
  push:
    branches:
      - develop
    paths:
      - client/**
  workflow_dispatch:

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
      name: Check out code

    - uses: mr-smithers-excellent/docker-build-push@v4
      name: Build & push Docker image
      with:
        image: 7studsclient
        tag: latest
        registry: ${{ secrets.DOCKER_URL }}
        directory: ./client
        dockerfile: ./client/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildArgs: SERVER_URL=${{ secrets.SERVER_URL }}
