name: ci

on:
  push:
    branches: develop

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
      name: Check out code

    - uses: mr-smithers-excellent/docker-build-push@v4
      name: Build & push Docker image
      with:
        image: 7studsacr.azurecr.io/7studsserver
        tag: latest
        registry: 7studsacr.azurecr.io
        dockerfile: ./client/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
